version: '3.8'

services:
  frontend:
    build:
      context: . # Root directory, where the Nginx Dockerfile is
      dockerfile: Dockerfile # Explicitly name the Dockerfile for Nginx
    ports:
      - "8080:80" # Map host port 8080 to container port 80 (Nginx default)
    depends_on:
      - backend
    networks:
      - calendar_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env # Load environment variables from .env file
    environment:
      NODE_ENV: development
      PORT: 3001
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    networks:
      - calendar_network


networks:
  calendar_network: # Define the custom network
    driver: bridge
